=== hcab14/HFMonitor/config/DTD/client_multi.dtd
<!-- client_multi configuration -->
<!-- $Id$ -->

<!ELEMENT ClientMulti (Servers+,Python)>
<!ATTLIST ClientMulti time_granularity_sec      CDATA #REQUIRED> <!-- time interval in which data is collected  -->
<!ATTLIST ClientMulti synchronization_delay_sec CDATA #REQUIRED> <!-- processing delay due to network latency  -->
<!ATTLIST ClientMulti threadPoolSize            CDATA #IMPLIED>  <!-- number of threads used, default=4  -->

<!ELEMENT Servers (Server+)>              <!-- list of servers to connect to -->

<!ELEMENT Server (Stream+)>               <!-- single server configuration -->
<!ATTLIST Server name CDATA #REQUIRED>    <!-- name used as prefix of stream names  -->
<!ATTLIST Server host CDATA #REQUIRED>    <!-- host -->
<!ATTLIST Server port CDATA #REQUIRED>    <!-- port -->

<!ELEMENT Stream (#PCDATA)>               <!-- stream - processor name association -->
<!ATTLIST Stream pattern CDATA #REQUIRED> <!-- pattern matching available stream names -->

<!-- python adapter configuration: cf. external DTD -->
<!ENTITY % Python-DTD SYSTEM "python.dtd">
%Python-DTD;

=== hcab14/HFMonitor/test/client_multi.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ClientMulti SYSTEM "DTD/client_multi.dtd">
<!-- $Id$ -->
<!-- this file was used for testing client_multi_base in KRK -->
<ClientMulti time_granularity_sec="1" synchronization_delay_sec="5">
  <Servers>
    <Server name="KRK" host="nz23-18.ifj.edu.pl" port="8080">
      <Stream pattern="L.*">ProcessorName</Stream>
      <Stream pattern="M.*">ProcessorName</Stream>
    </Server>
    <Server name="BOS" host="localhost" port="19026">
      <Stream pattern="L.*">ProcessorName</Stream>
      <Stream pattern="M.*">ProcessorName</Stream>
    </Server>
  </Servers>
</ClientMulti>

=== hcab14/HFMonitor/config/client_multi_python_NTZ.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ClientMulti SYSTEM "DTD/client_multi.dtd"> 
<!-- $Id: multi_client_STA.xml 399 2014-05-14 20:43:43Z cmayer $ -->

<ClientMulti 
   time_granularity_sec="1"
   synchronization_delay_sec="3"
   threadPoolSize="4">
  <Servers>
    <Server name="TWN" host="cpcfcmd.evn.np.kn.nz.dlr.de" port="40044">
      <Stream pattern="M.*"></Stream>
<!--  <Stream pattern="L.*"></Stream>  -->
    </Server>
    <Server name="STA" host="cpcfcmd.evn.np.kn.nz.dlr.de" port="40029">
      <Stream pattern="M.*"></Stream>
<!--  <Stream pattern="L.*"></Stream>  -->
    </Server>
    <Server name="BOS" host="cpcfcmd.evn.np.kn.nz.dlr.de" port="40026">
      <Stream pattern="M.*"></Stream>
<!--  <Stream pattern="L.*"></Stream>  -->
    </Server>
  </Servers>
  <Python
     pkg="example_pkg"
     file="proc"
     fcn="process_data_per_interval">
  </Python>
</ClientMulti>
