=== hcab14/HFMonitor/HFMonitor/config/DTD/multi_client.dtd
<!-- multi_client configuration -->
<!-- $Id$ -->

<!ELEMENT MultiClient (StationInfo,Broadcaster*,server,FileSink,Streams,Clients)>

<!-- Station information for headers of data files -->
<!ELEMENT StationInfo (#PCDATA)>

<!-- Broadcaster configuration: cf. external DTD -->
<!ENTITY % Broadcaster-DTD SYSTEM "broadcaster.dtd">
%Broadcaster-DTD;

<!-- Client configuration: cf. external DTD -->
<!ENTITY % server-DTD SYSTEM "server.dtd">
%server-DTD;

<!-- file writer configuration -->
<!ELEMENT FileSink EMPTY>
<!ATTLIST FileSink filePath   CDATA         #REQUIRED> <!-- path name -->
<!ATTLIST FileSink filePeriod (1d|1h|5m|1m) #REQUIRED> <!-- time periods -->

<!-- stream configuration -->
<!ELEMENT Streams (Stream+)>
<!ELEMENT Stream (#PCDATA)> <!-- processor name -->
<!ATTLIST Stream pattern CDATA #REQUIRED> <!-- regular expression specifying for which streams the processor should be run-->

<!ELEMENT Clients (WriterTXT|WriterIQ|DemodFSK|DemodMSK|FFT_Processor)*>

<!-- text writer processor configuration: cf. external DTD -->
<!ENTITY % WriterTXT-DTD SYSTEM "WriterTXT.dtd">
%WriterTXT-DTD;

<!-- I/Q wav writer processor configuration: cf. external DTD -->
<!ENTITY % WriterIQ-DTD SYSTEM "WriterIQ.dtd">
%WriterIQ-DTD;

<!-- DemodFSK processor configuration: cf. external DTD -->
<!ENTITY % DemodFSK-DTD SYSTEM "DemodFSK.dtd">
%DemodFSK-DTD;

<!-- DemodMSK processor configuration: cf. external DTD -->
<!ENTITY % DemodMSK-DTD SYSTEM "DemodMSK.dtd">
%DemodMSK-DTD;

<!-- FFT_Processor processor configuration: cf. external DTD -->
<!ENTITY % FFT_Processor-DTD SYSTEM "FFT_Processor.dtd">
%FFT_Processor-DTD;

=== hcab14/HFMonitor/config/multi_client_writer_NTZ_fromHER.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE MultiClient SYSTEM "DTD/multi_client.dtd"> 
<!-- $Id: multi_client_writer_NTZ_fromSTA.xml 399 2014-05-14 20:43:43Z cmayer $ -->
<MultiClient>
  <StationInfo>
    Station  = NTZ
    Computer = Latitude E6440 : N-Series Base
  </StationInfo>
  <server host="cpcfcmd.evn.np.kn.nz.dlrx.de" port="40044"/>
  <FileSink filePath="DataHER" filePeriod="1d"/>
  <Streams>
    <Stream pattern="A.*">Writer</Stream>
    <Stream pattern="L.*">Writer</Stream>
    <Stream pattern="M.*">Writer</Stream>
  </Streams>
  <Clients>
    <WriterTXT proc_name="Writer" filePath="DataHER" filePeriod="1d"/>
  </Clients>
</MultiClient>
