=== hcab14/HFMonitor/tags/HFMonitor_v3.0/config/DTD/multi_downconvert.dtd
<!-- multi downconverter configuration -->
<!-- $Id$ -->

<!ELEMENT MultiDownConverter (StationInfo,Broadcaster,Repack,server,Calibration,Processors,Filters)>
<!ATTLIST MultiDownConverter l CDATA #REQUIRED> <!-- number of samples processed in one epoch == Repack specification -->
<!ATTLIST MultiDownConverter m CDATA #REQUIRED> <!-- typically m is l/4 + 1 -->

<!-- Station information for headers of data files -->
<!ELEMENT StationInfo (#PCDATA)>

<!-- Broadcaster configuration: cf. external DTD -->
<!ENTITY % Broadcaster-DTD SYSTEM "broadcaster.dtd">
%Broadcaster-DTD;

<!-- Repack Processor configuration -->
<!ELEMENT Repack EMPTY>
<!ATTLIST Repack bufferLength_sec CDATA #REQUIRED> <!-- length of buffer (sec) -->
<!ATTLIST Repack overlap_percent  CDATA #REQUIRED> <!-- overlap between epochs (%) -->

<!-- Client configuration: cf. external DTD -->
<!ENTITY % server-DTD SYSTEM "server.dtd">
%server-DTD;

<!-- frequency calibration configuration -->
<!ELEMENT Calibration (Key+)>
<!ATTLIST Calibration algorithm (WeightedMean) #REQUIRED> <!-- for now only weighted mean algorithm is available -->
<!ELEMENT Key (#PCDATA)>                                  <!-- keys referencing processors specified below -->

<!-- calibration processor configuration -->
<!ELEMENT Processors (TrackingGoertzel+)>

<!-- TrackingGoertzel processor configuration: cf. external DTD -->
<!ENTITY % TrackingGoertzel-DTD SYSTEM "TrackingGoertzel.dtd">
%TrackingGoertzel-DTD;

<!ELEMENT Filters (FIR+)>
<!ELEMENT FIR EMPTY>
<!ATTLIST FIR name               CDATA     #REQUIRED> <!-- filter name  -->
<!ATTLIST FIR type               (lowpass) #REQUIRED> <!-- filter type -->
<!ATTLIST FIR cutoff             CDATA     #REQUIRED> <!-- filter cutoff (normalized frequency) -->
<!ATTLIST FIR centerFrequency_Hz CDATA     #REQUIRED> <!-- center frequency (Hz) -->
<!ATTLIST FIR decim              CDATA     #REQUIRED> <!-- decimation factor -->

=== hcab14/HFMonitor/tags/HFMonitor_v3.1/config/multi_downconvert_KRK.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE MultiDownConverter SYSTEM "DTD/multi_downconvert.dtd"> 
<!-- $Id$ -->
<MultiDownConverter l="500000"
                    m="125001">
  <StationInfo>
    Station  = KRK
    Computer = Linux nz23-18.ifj.edu.pl 2.6.32.27
  </StationInfo>
  <Broadcaster>
    <Data maxQueueSize_MB="200"
          maxQueueDelay_Minutes="2"
          port="19100"/>
  </Broadcaster>
  <Repack bufferLength_sec="1" overlap_percent="0"/>
  <server host="nz23-18.ifj.edu.pl" port="19090" stream_name="DC_0220000_LW"/>
  <Calibration>
    <Algorithm type="WeightedMean">
      <Key>TGF_MSF</Key>
      <Key>TGF_DCF77</Key>
    </Algorithm>
  </Calibration>
  <Processors>
    <TrackingGoertzel name="TGF_MSF"
                      input="DC_060000_MSF"
                      f0_Hz="60.0e3"
                      df_Hz="5.0"
                      minDf_Hz=".1"
                      maxHistorySize="120"
                      maxNumWithoutLock="2"/>
    <TrackingGoertzel name="TGF_DCF77"
                      input="DC_077500_DCF"
                      f0_Hz="77.5e3"
                      df_Hz="5.0"
                      minDf_Hz=".1"
                      maxHistorySize="120"
                      maxNumWithoutLock="2"/>
  </Processors>
  <Filters>
    <FIR name="DC_016400_JXN"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 16.40e3" decim="100"/>
    <FIR name="DC_019600_GQD"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 19.60e3" decim="100"/>
    <FIR name="DC_019800_NWC"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 19.80e3" decim="100"/>
    <FIR name="DC_020270_ICV"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 20.27e3" decim="100"/>
    <FIR name="DC_021750_HWU"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 21.75e3" decim="100"/>
    <FIR name="DC_022100_GQD"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 22.10e3" decim="100"/>
    <FIR name="DC_023400_DHO"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 23.40e3" decim="100"/>
    <FIR name="DC_024000_NAA"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 24.00e3" decim="100"/>
    <FIR name="DC_026000_XXX"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 26.00e3" decim="100"/>
    <FIR name="DC_026700_TBB"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 26.70e3" decim="100"/>
    <FIR name="DC_037500_NRK"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 37.50e3" decim="100"/>
    <FIR name="DC_045900_NSY"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 45.90e3" decim="100"/>
    <FIR name="DC_049000_SXA"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 49.00e3" decim="100"/>
    <FIR name="DC_057400_GXH"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 57.40e3" decim="100"/>
    <FIR name="DC_060000_MSF"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 60.00e3" decim="100"/>
    <FIR name="DC_063850_FTA"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 63.85e3" decim="100"/>
    <FIR name="DC_065800_FUE"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 65.80e3" decim="100"/>
    <FIR name="DC_077500_DCF"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 77.50e3" decim="100"/>
    <FIR name="DC_081000_GYN"  type="lowpass" cutoff="0.009" centerFrequency_Hz=" 81.00e3" decim="100"/>
    <FIR name="DC_020000_MSKs" type="lowpass" cutoff="0.018" centerFrequency_Hz=" 20.00e3" decim=" 50"/>
    <FIR name="DC_030000_MSKs" type="lowpass" cutoff="0.018" centerFrequency_Hz=" 30.00e3" decim=" 50"/>
    <FIR name="DC_040000_MSKs" type="lowpass" cutoff="0.018" centerFrequency_Hz=" 40.00e3" decim=" 50"/>
    <FIR name="DC_050000_MSKs" type="lowpass" cutoff="0.018" centerFrequency_Hz=" 50.00e3" decim=" 50"/>
    <FIR name="DC_060000_MSKs" type="lowpass" cutoff="0.018" centerFrequency_Hz=" 60.00e3" decim=" 50"/>
    <FIR name="DC_070000_MSKs" type="lowpass" cutoff="0.018" centerFrequency_Hz=" 70.00e3" decim=" 50"/>
    <FIR name="DC_080000_MSKs" type="lowpass" cutoff="0.018" centerFrequency_Hz=" 80.00e3" decim=" 50"/>
    <FIR name="DC_292000_DGPS" type="lowpass" cutoff="0.036" centerFrequency_Hz="292.00e3" decim=" 25"/>
    <FIR name="DC_132000_EFR"  type="lowpass" cutoff="0.036" centerFrequency_Hz="132.00e3" decim=" 25"/>
  </Filters>
</MultiDownConverter>
